
#this program parses a tsv file with accession, BV-BRC genome Id and host group (generated by Christian Zmasek)
#extract the accession and fetch sequence from Entrez. Output is a text file with accession and sequence


#install Biopython
import csv
from Bio import Entrez, SeqIO

def fetch_genbank_file(accession):
    # Provide your email address for identification
    Entrez.email = "rbhattac@jcvi.org"

    # Fetch the GenBank record using the accession number
    handle = Entrez.efetch(db="nucleotide", id=accession, rettype="gb", retmode="text")

    # Parse the GenBank record
    record = SeqIO.read(handle, "genbank")

    # Close the handle
    handle.close()

    return record



def main():

    file_path = '/Users/rbhattac/Desktop/outfile.tsv'
    #output_file_path = '/Users/rbhattac/Desktop/outfile_seq.tsv'

    # Write to the output TSV file
    #with open(output_file_path, 'w', newline='', encoding='utf-8') as output_tsvfile:
       #tsvwriter = csv.writer(output_tsvfile, delimiter='\t')

    f = open("/Users/rbhattac/Desktop/test_output.txt", "w")


    with open(file_path, 'r', newline='', encoding='utf-8') as tsvfile:
        # Use the csv.reader and specify the delimiter as '\t' for TSV files
        tsvreader = csv.reader(tsvfile, delimiter='\t')
        count = 0
         # Iterate over each row in the TSV file
        for row in tsvreader:
            accession_number = row[0]
            f.write(">"+accession_number+"\n")
            genbank_record = fetch_genbank_file(accession_number)
            sequence = genbank_record.seq
            f.write(str(sequence)+"\n")
            count = count+1
            print(count)

            #print(sequence)

            #print([accession_number, sequence])
            # Write a row with accession and sequence
            #tsvwriter.writerow([accession_number, sequence])
    f.close()
if __name__ == "__main__":
    main()
# Example usage:
#file_path = '/Users/rbhattac/Desktop/outfile.tsv'
#parse_tsv_file(file_path)